FROM ubuntu:20.04
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils ca-certificates wget unzip git git-lfs python3 python3-pip python-is-python3 pip
RUN pip install nibabel torch statsmodels
RUN update-ca-certificates
WORKDIR /anima/
RUN wget -q https://github.com/Inria-Visages/Anima-Public/releases/download/v4.0.1/Anima-Ubuntu-4.0.1.zip
RUN unzip Anima-Ubuntu-4.0.1.zip
RUN git lfs install
RUN git clone --depth 1 https://github.com/Inria-Visages/Anima-Scripts-Data-Public.git
RUN mkdir /root/.anima/
RUN mkdir /anima/WEIGHTS
RUN mkdir /tmp/test_image
RUN wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Uhua7GKeENnNK_VRH6tDAFksluC-wRMc' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Uhua7GKeENnNK_VRH6tDAFksluC-wRMc" -O decoder_FMs_iqda_for_new_lesions.zip && rm -rf /tmp/cookies.txt
RUN unzip decoder_FMs_iqda_for_new_lesions.zip
RUN git clone https://github.com/Reda-Abdellah/new_lesions_public.git
RUN cp -avr new_lesions_public/Anima-Scripts-Public /anima/Anima-Scripts-Public
RUN cp new_lesions_public/config.txt /root/.anima
RUN cp -avr new_lesions_public/Registration /anima/Registration
RUN cp CHALLENGE_IQDA_v2_DECODE_with_FMs/* /anima/WEIGHTS
RUN cp new_lesions_public/*.py /anima/
RUN mkdir -p /data/patients/patient_X/

